@startuml
title Diagramme de séquence — Traitement d'une requête HTTP


participant "E : Ecouteur" as E
participant "H : Handler" as H
participant "FS : Système fichiers" as FS
participant "C : Client" as C

 -> E : connexion TCP
E -> H : new Handler(ps).start()
activate H

 -> H : GET /index.html HTTP/1.1

H -> FS : lire fichier
FS --> H : contenu fichier

H -> H : calculerETag(contenu)


H -> C : HTTP 200 OK + ETag + contenu
H -> H : ecrireLog(accesLog, "200 OK")
 <-- H: affichage effectuer
deactivate H


@enduml